### ISSUE TITLE
Extending functionality

### ISSUE THREAD

**Issue by MikiDylewski** [dentolos19/AniListNet#3]
Geya, so been recently digging through the code, as you could realise with the PR, and been trying to extend the functionality of this package a bit. Right now what I'm trying to do is to get users MediaListCollection with
```graphql
query {
  MediaListCollection(userId: 165049, type: ANIME) {
    lists {
      name
      isCustomList
      status
    }
  }
}
```
So i tried doing (based on #GetUserEntryCollectionAsync) this
```csharp
//AniClient.User.cs
public async Task<MediaListCollection[]> GetUserMediaListCollection(int userId, MediaType type)
    {
        var selections = new GqlSelection("MediaListCollection", typeof(MediaListCollection).ToSelections(), new GqlParameter[]
        {
            new("userId", userId),
            new("type", type),
        });
        
        var response = await PostRequestAsync(selections);
        return response["MediaListCollection"].ToObject<MediaListCollection[]>();
    }
    //MediaListCollection
public class MediaListCollection
{
    [JsonProperty("lists")] public MediaList[] Lists;
}

//MediaList
public class MediaList
{
    [JsonProperty("name")] public string Name { get; private set; }
    [JsonProperty("isCustomList")] public string IsCustom{ get; private set; }
    [JsonProperty("status")] public MediaEntryStatus? Status{ get; private set; }
}
```
    Error that I'm getting right now: `Field "MediaListCollection" of type "MediaListCollection" must have a sub selection.`
    Thanks in advance

**Comment by dentolos19** [comment]
The issue should be fixed by making your `Lists` field into a property.

```cs
public class MediaListCollection
{
    [JsonProperty("lists")] public MediaList[] Lists { get; private set; }
}
```

This is regarding to how sub selections inside a class are parsed. From this [code](https://github.com/dentolos19/AniListNet/blob/d8f8bfe3d384b452cfee3090eaa8460a250646b5/AniListNet/Helpers/GqlParser.cs#L37-L41), you can see sub selections are selected by only two types, fields and properties. In your case, `Lists` was already a field, however in this [code](https://github.com/dentolos19/AniListNet/blob/d8f8bfe3d384b452cfee3090eaa8460a250646b5/AniListNet/Helpers/GqlParser.cs#L31), there is a rule where only non-public (private) fields are identified whereas public fields are ignored.

Hope this solves your issue.

**Comment by MikiDylewski** [comment]
Thanks for help and sorry for late response.
I'm closing this issue as I've done what i needed to do thanks to your help!
